/* Generated by dev/native-accessibility/tools/build_dw2_menu_assets.py.
 * Source: accessibility_profiles/digimon_world_2_menus.json
 * Profile SHA-256: 5c85b974838512f18848bcf34722dab4305e3914a1d2e283e4eb2bfd9b4b94e2
 */
#include "accessibility_dw2_menu_profile.h"

#include <stddef.h>

const char beetle_accessibility_dw2_menu_profile_hash[] = "5c85b974838512f18848bcf34722dab4305e3914a1d2e283e4eb2bfd9b4b94e2";

static const beetle_dw2_overlay_signature_t dw2_overlay_signatures[] = {
   { 0x00000190u, 0x80063360u, 26624u, 0x80063360u, { 0x80063adcu, 0x80063b30u, 0x80063b94u, 0x80063becu } }, /* STAG0000 */
   { 0x00000191u, 0x80063360u, 12288u, 0x80063360u, { 0x4345444du, 0x7365725fu, 0x61623a74u, 0x706f2064u } }, /* STAG1000 */
   { 0x00000192u, 0x80063360u, 57344u, 0x80063360u, { 0x80064078u, 0x80064134u, 0x80064264u, 0x800642c4u } }, /* STAG2000 */
   { 0x00000193u, 0x80063360u, 69632u, 0x80063360u, { 0x80063d04u, 0x80063d04u, 0x80063d04u, 0x80063d04u } }, /* STAG3000 */
   { 0x0000019au, 0x80063360u, 65536u, 0x80063360u, { 0x01fb01f8u, 0x01f501feu, 0x02050202u, 0x01fc01f9u } }, /* STAG4000 */
   { 0x00000d1eu, 0x80063360u, 22528u, 0x80063360u, { 0x80064b70u, 0x80064bccu, 0x80064bccu, 0x80064b88u } }, /* STAG1100 */
   { 0x00000d4du, 0x80063360u, 32768u, 0x80063360u, { 0x8006380cu, 0x8006380cu, 0x8006380cu, 0x8006380cu } }, /* STAG3500 */
};

static const beetle_dw2_menu_probe_rule_t dw2_menu_probe_rules[] = {
   { 0x800128f4u, 0x00000000u, 7, 5, 17, 255, 255, 255, 0, 87, 0x00000031u },
   { 0x800129a8u, 0x00000000u, 7, 5, 20, 255, 255, 255, 0, 87, 0x00000031u },
   { 0x800138c0u, 0x00000000u, 4, 3, 4, 255, 255, 5, 0, 255, 0x00000010u },
   { 0x8001acd4u, 0x00000000u, 8, 6, 18, 255, 17, 22, 0, 255, 0x00000031u },
};

const beetle_dw2_menu_probe_rule_t *
beetle_accessibility_dw2_menu_rule_lookup(uint32_t pc,
      uint32_t overlay_tag)
{
   size_t low = 0;
   size_t high = sizeof(dw2_menu_probe_rules) / sizeof(dw2_menu_probe_rules[0]);
   while (low < high)
   {
      size_t middle = low + (high - low) / 2;
      const beetle_dw2_menu_probe_rule_t *rule = &dw2_menu_probe_rules[middle];
      if (overlay_tag < rule->overlay_tag
            || (overlay_tag == rule->overlay_tag && pc < rule->pc))
         high = middle;
      else if (overlay_tag > rule->overlay_tag
            || (overlay_tag == rule->overlay_tag && pc > rule->pc))
         low = middle + 1;
      else
         return rule;
   }
   return NULL;
}

const beetle_dw2_overlay_signature_t *
beetle_accessibility_dw2_overlay_signatures(size_t *count)
{
   if (count)
      *count = sizeof(dw2_overlay_signatures) / sizeof(dw2_overlay_signatures[0]);
   return dw2_overlay_signatures;
}

const char *beetle_accessibility_dw2_icon_label(uint32_t resource_id)
{
   switch (resource_id)
   {
      case 0x01fd0061u:
         return "Status";
      case 0x01fd0062u:
         return "Items";
      case 0x01fd0063u:
         return "Digimon";
      case 0x01fd0064u:
         return "Digi-Line";
      case 0x01fd0065u:
         return "Transfer";
      case 0x01fd0066u:
         return "Save";
      case 0x01fd0067u:
         return "Auto-Pilot";
      default:
         return NULL;
   }
}

const char *beetle_accessibility_dw2_context_name(uint8_t context)
{
   switch (context)
   {
      case 0:
         return "none";
      case 1:
         return "system";
      case 2:
         return "domain_select";
      case 3:
         return "domain_circle";
      case 4:
         return "list";
      case 5:
         return "prompt";
      case 6:
         return "battle";
      case 7:
         return "name_entry";
      case 8:
         return "dialogue_choice";
      default:
         return NULL;
   }
}

size_t beetle_accessibility_dw2_menu_rule_count(void)
{
   return sizeof(dw2_menu_probe_rules) / sizeof(dw2_menu_probe_rules[0]);
}
